### ISSUE TITLE
support Qt6

### ISSUE THREAD

**Issue by MehdiChinoune** [ig-or/qwtw#3]

**Comment by ig-or** [comment]
will try when will have time.. also, several bug fixes have to be committed..

what qt6 version are you aiming at? also, are you going to use this library directly or via Julia language wrapper? or Python?

never worked with qt6 but it should be possible to make qt6 version. 

Best regards

**Comment by MehdiChinoune** [comment]
Just asking, I want to update on vcpkg against Qt6.

**Comment by ig-or** [comment]
So you were able to compile it eventually?

**Comment by MehdiChinoune** [comment]
No, I have an habitude to close issues that do not get fixed in a certain time.
